version: "3"
services:
  db:
    image: postgres
    container_name: cardgame-db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  cardgame:
    build:
      context: .
      dockerfile: ./docker/Docker.server/Dockerfile
    image: cardgame
    env_file: .env
    container_name: cardgame
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db:postgres
