# Generated by Django 3.2 on 2021-05-14 04:14

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("TWO", "Two"),
                            ("THREE", "Three"),
                            ("FOUR", "Four"),
                            ("FIVE", "Five"),
                            ("SIX", "Six"),
                            ("SEVEN", "Seven"),
                            ("EIGHT", "Eight"),
                            ("NINE", "Nine"),
                            ("TEN", "Ten"),
                            ("JACK", "Jack"),
                            ("QUEEN", "Queen"),
                            ("KING", "King"),
                            ("ACE", "Ace"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "suit",
                    models.CharField(
                        choices=[
                            ("CLUB", "Club"),
                            ("DIAMOND", "Diamond"),
                            ("HEART", "Heart"),
                            ("SPADE", "Spade"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="UserGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cards_drawn",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("WIN", "Win"), ("LOSS", "Loss"), ("IN_PROGRESS", "In Progress")],
                        default="IN_PROGRESS",
                        max_length=16,
                    ),
                ),
                (
                    "deck",
                    models.ForeignKey(
                        default=game.models.get_default_deck,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.deck",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeckCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "card",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="game.card"),
                ),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="game.deck",
                    ),
                ),
            ],
        ),
    ]
